version: '3'

services:
        nginx:
                build:
                    dockerfile: dockerfile-nginx
                    context: ./nginx
                ports: 
                        - "80:80"
                links:
                        - phpfpm
                depends_on:
                        - mysql    
                volumes:
                        - ./public:/var/www/html
                        - ./conf/default:/etc/nginx/conf.d/default.conf
                        - ./logs/nginx-error.log:/var/log/nginx/error.log
                        - ./logs/nginx-access.log:/var/log/nginx/access.log        
                container_name: nginxrik    
                networks:
                        - network-dockernginxrik
        phpfpm:
                build:
                    dockerfile: dockerfile-php
                    context: ./php
                ports:
                        - "9000:9000" 
                links:
                        - mysql            
                container_name: phprik
                env_file:
                    - ".env"        
                volumes:
                        - ./public:/var/www/html         
                networks:
                        - network-dockernginxrik
        mysql:
                image: mysql:latest
                container_name: mysqlrik
                restart: always
                volumes:
                        - ./public:/var/www/html
                        - ./db:/var/lib/mysql
                environment:
                        MYSQL_ROOT_PASSWORD: adm1n
                        MYSQL_DATABASE: ijd
                        MYSQL_USER: fatih
                        MYSQL_PASSWORD: 1234
                command: --innodb-use-native-aio=0  mysql --default-authentication-plugin=mysql_native_password   mysql -uroot --protocol tcp      
                ports:
                        - "3306:3306" 
                networks:
                        - network-dockernginxrik               
networks:
        network-dockernginxrik:
                driver: bridge
