version: '3'

services:
        nginx:
                build:
                    dockerfile: dockerfile-nginx
                    context: ./nginx
                ports: 
                        - "80:80"
                links:
                        - phpfpm
                volumes:
                        - ./public:/var/www/html
                        - ./conf/default:/etc/nginx/conf.d/default.conf
                        - ./logs/nginx-error.log:/var/log/nginx/error.log
                        - ./logs/nginx-access.log:/var/log/nginx/access.log        
                container_name: nginxrik    
                networks:
                        - network-dockernginxrik
        phpfpm:
                build:
                    dockerfile: dockerfile-php
                    context: ./php
                ports:
                        - "9000:9000"       
                container_name: phprik        
                volumes:
                        - ./public:/var/www/html         
                networks:
                        - network-dockernginxrik
        mysql:
                image: mariadb
                container_name: mysqlrik
                volumes:
                        - ./public:/var/www/html  
                environment:
                        MYSQL_ROOT_PASSWORD: adm1n
                        MYSQL_DATABASE: ijd
                        MYSQL_USER: fatih
                        MYSQL_PASSWORD: 1234
                ports:
                        - "3306:3306"
                networks:
                        - network-dockernginxrik        
networks:
        network-dockernginxrik:
                driver: bridge
