
FROM php:7.2.1-fpm
MAINTAINER Iwan Susanto (iwandevapps@gmail.com)

RUN apt-get update && \
	apt-get -y install \
	libpng-dev \
	libpq-dev \
	libxml2-dev \
	libcurl3-dev \
	libjpeg-dev \
    libjpeg62-turbo-dev \
	libfreetype6-dev \
	libicu-dev \
	zlib1g-dev \
	curl \
	g++ \
	git \
	vim-tiny \
	nano \
	unzip \
	openssh-client \
		--no-install-recommends && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN docker-php-ext-configure intl && \
	docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/

RUN docker-php-ext-install \
	pdo_mysql \
	pdo_pgsql \
	mbstring \
	gd \
	zip \
	opcache \
	curl \
	intl \
	soap


#RUN sendmail -bd

# Install Composer
RUN cd /tmp && curl -sS https://getcomposer.org/installer | php && \
	mv composer.phar /usr/local/bin/composer
	
	
#install Imagemagick & PHP Imagick ext
#RUN apt-get update && apt-get install -y \
#        libmagickwand-dev --no-install-recommends

#RUN pecl install imagick && docker-php-ext-enable imagick

	
# Install PECL extensions
# see http://stackoverflow.com/a/8154466/291573) for usage of `printf`
#RUN printf "\n" | pecl install \
#        imagick && \
#    docker-php-ext-enable \
#        imagick && \
#	rm -r /var/lib/apt/lists/*
		
